name: provider_signin_playground
description: provider_signin_playground

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: 0.9.3
  flutter_lints: 2.0.1
  intl: 0.17.0
  flutter_layout_grid: 2.0.1
  go_router: 5.0.0
  flutter_riverpod: 2.0.0-dev.9
  rxdart: 0.27.4
  sembast: 3.2.0
  sembast_web: 2.0.1+1
  path_provider: 2.0.10
  freezed_annotation: 2.1.0
  
dev_dependencies:
  build_runner: 2.2.0
  flutter_test:
    sdk: flutter
  freezed: 2.1.0+1
  integration_test:
    sdk: flutter
  mocktail: 0.3.0
  
flutter:
  uses-material-design: true